[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fsdeepnet"
version = "0.1"
dependencies= [
    #'torch',
    #'torchvision<0.17',  # to satisfy torch 2.1.2
    'psutil',
    'wandb',
    #'PyQt5',  # for matplotlib
    #'pynvml',
    #'voxynth@git+https://github.com/dalcalab/voxynth.git@main'
]

[project.scripts]
fsdeepnet_train = 'fsdeepnet.cli.fsdeepnet_train:main'
fsdeepnet_predict = 'fsdeepnet.cli.fsdeepnet_predict:main'
fsdeepnet_evaluate = 'fsdeepnet.cli.fsdeepnet_evaluate:main'
fsdeepnet_create_data_list = 'fsdeepnet.cli.fsdeepnet_create_data_list:main'
fsdeepnet_checkpoint = 'fsdeepnet.cli.fsdeepnet_checkpoint:main'
fsdeepnet_test_dataset = 'fsdeepnet.cli.test_dataset:main'
fsdeepnet_test_dataloader = 'fsdeepnet.cli.test_dataloader:main'
fsdeepnet_tf2torch = 'fsdeepnet.cli.tf2torch.loadh5_synthseg:main'
