dataset:
  dataset_classname: fsdeepnet.datasets.segmentationdataset.SegmentationDataset
  segmentation_labels: [0, 1]
  expected_num_channels: 1

model:
  name: fsdeepnet.models.unet.UNet
  nb_levels: 3
  nb_features: 24 
  feat_mult: 2
  nb_conv_per_level: 2
  norm: batch
  track_running_stats: False
  activation: elu
  ndims: 3
  conv_size: 3
  pool_size: 2
  use_residuals: False
  final_pred_activation: softmax
  weight_init: xavier_uniform
  upsample_interpolation: linear

preprocessing:
  augmentation_class: fsdeepnet.augmentation.augmentbase.AugmentBase
  crop_size: [64, 64, 64]
  augmentations:
    - spatialdeformation:
        affine_probability: 0.5
        max_translation: 30
        max_rotation: 20
        max_shearing: 0.015  
        max_scaling: 1.2
        warp_probability: 0.5
        warp_integrations: 7
        warp_generation_method: "upsample"
        warp_smoothing_range: [10.62, 10.62]
        warp_magnitude_range: [0, 3]
    - centercrop:
    - biasfieldcorruption:
        bias_field_probability: 0.5
        bias_field_max_magnitude: 0.5
        bias_field_scale: 0.025
    - intensityaugmentation:
        added_noise_probability: 0.5
        added_noise_max_sigma: 1.0
        gamma_scaling_probability: 0.5
        gamma_scaling_max: 0.59

training:
  dice_epochs: 10
  wl2_epochs: 0
  steps_per_epoch: 100
  batch_size: 1
  learning_rate: 0.0001
  pre_train_learning_rate: 0.0001
  optimizer: torch.optim.Adam
  wl2_metrics: fsdeepnet.metrics.WeightedL2Loss
  model_metrics: fsdeepnet.metrics.DiceLoss
  perform_evaluation: True
  best_model_metric: dice

evaluation:
  batch_size: 1
