dataset:
  dataset_list_file: configs/multiclass_multichannel_dummy_dataset_list.yaml
  expected_classes: [0, 3, 5, 8]
  left_right_corresponding: None # ex. this is for SynthSeg training [2, 41, 3, 42, 4, 43, 5, 44, 7, 46, 8, 47, 10, 49, 11, 50, 12, 51, 13, 52, 17, 53, 18, 54, 25, 57, 26, 58, 28, 60, 30, 62, 136, 163, 137, 164]
  expected_num_channels: 2

model:
  name: UNet3D
  num_classes: 4
  nb_levels: 5
  nb_features: 24 
  feat_mult: 2
  nb_conv_per_level: 2
  use_batchnorm: True
  activation: "elu"
  ndims: 3
  conv_size: 3
  pool_size: 2
  use_residuals: False
  refine_conv: False 

preprocessing:
  augmentation_dir: None  # where to save the augmented data
  flip_prob: 0.5
  crop_size: [64, 64, 64]
  flip_axes: [1]
  max_translation: 0.5
  max_rotation: 5.0
  max_scaling: 1.1
  warp_probability: 0.25
  warp_integrations: 1
  warp_smoothing_range: [10, 20]
  warp_magnitude_range: [1, 2]
  smoothing_probability: 0.25
  smoothing_max_sigma: 2.0
  added_noise_probability: 0.5
  added_noise_max_sigma: 0.05
  gamma_scaling_probability: 0.5
  gamma_scaling_max: 0.8
  bias_field_probability: 0.25
  bias_field_max_magnitude: 0.1
  bias_field_smoothing_range: [1, 2]
  
training:
  num_epochs: 300
  pre_train_epochs: 5
  output_folder: output 
  batch_size: 1
  learning_rate: 0.0001
  pre_train_learning_rate: 0.001
  ignore_indexes: [0] # 0==background
  best_model_metric: dice

evaluation:
  output_folder: output/evaluation
  batch_size: 1