dataset:
  dataset_list_file: configs/pgland_dataset_list.yaml
  expected_classes: [0, 883, 900, 903, 904]
  #left_right_corresponding: define-left-right-label-correspondings #ex. this is for SynthSeg training [2, 41, 3, 42, 4, 43, 5, 44, 7, 46, 8, 47, 10, 49, 11, 50, 12, 51, 13, 52, 17, 53, 18, 54, 25, 57, 26, 58, 28, 60, 30, 62, 136, 163, 137, 164]
  expected_num_channels: 1

model:
  name: freeseg.models.unet.UNet
  nb_levels: 3
  nb_features: 24 
  feat_mult: 2
  nb_conv_per_level: 2
  use_batchnorm: True
  activation: "elu"
  ndims: 3
  conv_size: 3
  pool_size: 2
  use_residuals: False
  refine_conv: False
  final_pred_activation: "softmax"

preprocessing:
  augmentation_class: freeseg.augmentation.augmentbase.AugmentBase   # or freeseg.augmentation.augment2.Augment2
  sampling_hyperparameters: True
  verbose: False
  train_augmentations: [
    # "flip",          # need to define left_right_corresponding
    "spatialdeformation",
    # only one type of cropping should be listed
    "centercrop",            # crop around the image cener
    #"randomcrop",         # crop from a randomly selected point
    #"randomcentercrop",  # crop around a randomly selected point
    "biasfieldcorruption",
    "intensityaugmentation",
    ]
  #augmentation_dir: /path/to-save-augmented-data
  #bbox_labels: list of labels to make the bounding box
  flip_prob: 0.5
  crop_size: [160, 160, 160]
  
  # spatialtransform parameters (AugmentBase)
  affine_probability: 1.0
  max_translation: 30  # mm
  max_rotation: 20     # angles as degrees
  max_shearing: 0.015  
  max_scaling: 1.2     # scaling factor
  warp_probability: 1
  warp_integrations: 7
  warp_generation_method: "upsample"   # "blur" or "upsample"
  warp_smoothing_range: [10.62, 10.62]
  warp_magnitude_range: [0, 3]
  # to equate with hypothalamus/SynthSeg implementation,
  # 1. warp_generation_method: "blur"
  #    - voxel size of the hypothalamus/SynthSeg vector field
  #      voxelsize=1/nonlin_scale=25 (nonlin_scale=.04)
  #    - set fwhm=voxelsize
  #    - gstd=fwhm/sqrt(log(256))=25/sqrt(log(256))=10.62
  # 2. warp_generation_method: "upsample"
  #    warp_smoothing_range=1/nonlin_scale=25 (nonlin_scale=.04)

  
  # intensityaugmentation parameters (AugmentBase)
  added_noise_probability: 1 #0.5
  added_noise_max_sigma: 1.0
  gamma_scaling_probability: 1
  gamma_scaling_max: 0.59
  # to equate with augment2.IntensityAugmentation',
  # - set smoothing_probability=0, resized_probability=0,
  # - gamma_scaling_max is computed as following:
  #   a. in 'intensityAugmentation',
  #      gamma is randomly sampled from zero-mean gaussian distribution with fixed std=gamma_scaling_max
  #   b. here gamma is randomly sampled from uniform distribution between +-gamma_scaling_max
  #   c. set gamma_scaling_max to FWHM/2 of 'intensityAugmentation'
  #      gamma_scaling_max=FWHM/2=(gstd*sqrt(log(256.0)))/2=0.59
  smoothing_probability: 0   #0.25
  smoothing_max_sigma: 2.0
  resized_probability: 0
  resized_one_axis_probability: 0
  resized_max_voxsize: 2
  
  # biasfieldcorruption parameters (AugmentBase)
  bias_field_probability: 1 # Ben: turned on if bias_field_std > 0
  bias_field_max_magnitude: 0.5
  bias_field_smoothing_range: [16.98, 16.98]
  bias_field_generation_method: "blur"   # "blur" or "upsample"
  # to equate with augment2.BiasFieldCorruption, bias_field_smoothing_range is computed as following:
  # 1. bias_field_generation_method: "blur"
  #    - voxel size of the bias field in 'BiasFieldCorruption':   
  #      voxel_size=1/bias_scale=40 (bias_field_scale=.025)
  #    - set fwhm=voxelsize
  #    - gstd=fwhm/sqrt(log(256))=40/sqrt(log(256))=16.98
  # 2. bias_field_generation_method: "upsample:
  #    bias_field_smoothing_range=1/bias_scale=40 (bias_field_scale=.025)


  # sampleConditionalGMM parameters (AugmentBase)
  prior_mean: [25, 225]
  prior_std: [5, 25]
  prior_distribution: "uniform"

training:
  deterministic: False
  dice_epochs: 100
  wl2_epochs: 5
  steps_per_epoch: 1000
  train_output_folder: new_runs/tensorboard_logs   # Common parent directory for training output
  batch_size: 1
  learning_rate: 0.0001
  pre_train_learning_rate: 0.0001
  # define label index to be excluded from dice computation, 0=background
  # we compute background dice so it is set to empty []
  write_tensorboard_summary: False  # whether to output tensorboard logs
  perform_evaluation: False         # whether to perform evaluation after each epoch
  best_model_metric: dice           # metric to pick best model when perform_evaluation=True  

evaluation:
  evaluation_augmentations: [
    "cropping",
    ]
  test_augmentations: [
    "cropping",
  ]
  batch_size: 1
