dataset:
  dataset_classname: freeseg.datasets.segmentationdataset.SegmentationDataset
  segmentation_labels: [0, 883, 900, 903, 904]
  #left_right_corresponding: define-left-right-label-correspondings #ex. this is for SynthSeg training [2, 41, 3, 42, 4, 43, 5, 44, 7, 46, 8, 47, 10, 49, 11, 50, 12, 51, 13, 52, 17, 53, 18, 54, 25, 57, 26, 58, 28, 60, 30, 62, 136, 163, 137, 164]
  expected_num_channels: 1

model:
  name: freeseg.models.unet.UNet
  nb_levels: 3
  nb_features: 24 
  feat_mult: 2
  nb_conv_per_level: 2
  norm: batch  # or instance
  track_running_stats: False
  activation: elu
  ndims: 3
  conv_size: 3
  pool_size: 2
  use_residuals: False
  refine_conv: False
  final_pred_activation: softmax
  weight_init: xavier_uniform  # or zeros
  upsample_interpolation: linear  # linear or nearest
  skip_connect: norm    # norm or encoder

preprocessing:
  augmentation_class: freeseg.augmentation.augmentbase.AugmentBase   # or freeseg.augmentation.augmentvoxynth.AugmentVoxynth
  sampling_hyperparameters: True
  verbose: False
  crop_size: [160, 160, 160]
  target_res: 1  # in mm
  #augmentation_dir: /path/to-save-augmented-data
  #bbox_labels: list of labels to make the bounding box
  augmentations:
    #- flip:
    #    flip_prob: 0.5    
    - spatialdeformation:
        affine_probability: 1.0
        max_translation: 30  # mm
        max_rotation: 20     # angles as degrees
        max_shearing: 0.015  
        max_scaling: 1.2     # scaling factor
        warp_probability: 1
        warp_integrations: 7
        warp_generation_method: "upsample"   # "blur" or "upsample"
        warp_smoothing_range: [10.62, 10.62]
        warp_magnitude_range: [0, 3]
    # only one type of cropping should be listed
    - centercrop:           # crop around the image cener
    #- randomcrop           # crop from a randomly selected point
    #- randomcentercrop     # crop around a randomly selected point    
    - biasfieldcorruption:
        bias_field_probability: 1 # Ben: turned on if bias_field_std > 0
        bias_field_max_magnitude: 0.5
        bias_field_generation_method: "blur"   # this is for augmentvoxynth.biasfieldcorruption only, it is either "blur" or "upsample"
        bias_field_scale: 0.025
    - intensityaugmentation:
        added_noise_probability: 1 #0.5
        added_noise_max_sigma: 1.0
        gamma_scaling_probability: 1
        gamma_scaling_max: 0.59
    - gaussianblur:
        gaussian_blur_max_sigma: 2
        gaussian_blur_truncate: 2.5
    - mimicresolution:
        max_subsample_res: 4  # in mm
    #- resamplevolume:
    #- sampleConditionalGMM:
    #    prior_mean: [25, 225]
    #    prior_std: [5, 25]
    #    prior_distribution: "uniform"

training:
  deterministic: False
  dice_epochs: 100
  wl2_epochs: 5
  steps_per_epoch: 1000
  batch_size: 1
  learning_rate: 0.0001
  pre_train_learning_rate: 0.0001
  optimizer: torch.optim.Adam
  wl2_metrics: freeseg.metrics.WeightedL2Loss
  model_metrics: freeseg.metrics.DiceLoss
  write_tensorboard_summary: False  # whether to output tensorboard logs
  perform_evaluation: False         # whether to perform evaluation after each epoch
  best_model_metric: dice           # metric to pick best model when perform_evaluation=True  

evaluation:
  batch_size: 1
