test:
- image_filepath: data/dummy/images/image008.mgz
  label_filepath: data/dummy/labels/image008.mgz
- image_filepath: data/dummy/images/image010.mgz
  label_filepath: data/dummy/labels/image010.mgz
- image_filepath: data/dummy/images/image017.mgz
  label_filepath: data/dummy/labels/image017.mgz
- image_filepath: data/dummy/images/image012.mgz
  label_filepath: data/dummy/labels/image012.mgz
- image_filepath: data/dummy/images/image009.mgz
  label_filepath: data/dummy/labels/image009.mgz
train:
- image_filepath: data/dummy/images/image006.mgz
  label_filepath: data/dummy/labels/image006.mgz
- image_filepath: data/dummy/images/image023.mgz
  label_filepath: data/dummy/labels/image023.mgz
- image_filepath: data/dummy/images/image004.mgz
  label_filepath: data/dummy/labels/image004.mgz
- image_filepath: data/dummy/images/image007.mgz
  label_filepath: data/dummy/labels/image007.mgz
- image_filepath: data/dummy/images/image015.mgz
  label_filepath: data/dummy/labels/image015.mgz
- image_filepath: data/dummy/images/image011.mgz
  label_filepath: data/dummy/labels/image011.mgz
- image_filepath: data/dummy/images/image005.mgz
  label_filepath: data/dummy/labels/image005.mgz
- image_filepath: data/dummy/images/image029.mgz
  label_filepath: data/dummy/labels/image029.mgz
- image_filepath: data/dummy/images/image022.mgz
  label_filepath: data/dummy/labels/image022.mgz
- image_filepath: data/dummy/images/image024.mgz
  label_filepath: data/dummy/labels/image024.mgz
- image_filepath: data/dummy/images/image016.mgz
  label_filepath: data/dummy/labels/image016.mgz
- image_filepath: data/dummy/images/image001.mgz
  label_filepath: data/dummy/labels/image001.mgz
- image_filepath: data/dummy/images/image003.mgz
  label_filepath: data/dummy/labels/image003.mgz
- image_filepath: data/dummy/images/image020.mgz
  label_filepath: data/dummy/labels/image020.mgz
- image_filepath: data/dummy/images/image030.mgz
  label_filepath: data/dummy/labels/image030.mgz
- image_filepath: data/dummy/images/image028.mgz
  label_filepath: data/dummy/labels/image028.mgz
- image_filepath: data/dummy/images/image019.mgz
  label_filepath: data/dummy/labels/image019.mgz
- image_filepath: data/dummy/images/image021.mgz
  label_filepath: data/dummy/labels/image021.mgz
- image_filepath: data/dummy/images/image027.mgz
  label_filepath: data/dummy/labels/image027.mgz
- image_filepath: data/dummy/images/image025.mgz
  label_filepath: data/dummy/labels/image025.mgz
- image_filepath: data/dummy/images/image002.mgz
  label_filepath: data/dummy/labels/image002.mgz
validation:
- image_filepath: data/dummy/images/image018.mgz
  label_filepath: data/dummy/labels/image018.mgz
- image_filepath: data/dummy/images/image014.mgz
  label_filepath: data/dummy/labels/image014.mgz
- image_filepath: data/dummy/images/image026.mgz
  label_filepath: data/dummy/labels/image026.mgz
- image_filepath: data/dummy/images/image013.mgz
  label_filepath: data/dummy/labels/image013.mgz
