test:
- image_filepath: data/pitgland/binarized/images/image27.mgz
  label_filepath: data/pitgland/binarized/labels/image27.mgz
- image_filepath: data/pitgland/binarized/images/image15.mgz
  label_filepath: data/pitgland/binarized/labels/image15.mgz
- image_filepath: data/pitgland/binarized/images/image13.mgz
  label_filepath: data/pitgland/binarized/labels/image13.mgz
- image_filepath: data/pitgland/binarized/images/image14.mgz
  label_filepath: data/pitgland/binarized/labels/image14.mgz
- image_filepath: data/pitgland/binarized/images/image05.mgz
  label_filepath: data/pitgland/binarized/labels/image05.mgz
train:
- image_filepath: data/pitgland/binarized/images/image30.mgz
  label_filepath: data/pitgland/binarized/labels/image30.mgz
- image_filepath: data/pitgland/binarized/images/image18.mgz
  label_filepath: data/pitgland/binarized/labels/image18.mgz
- image_filepath: data/pitgland/binarized/images/image25.mgz
  label_filepath: data/pitgland/binarized/labels/image25.mgz
- image_filepath: data/pitgland/binarized/images/image04.mgz
  label_filepath: data/pitgland/binarized/labels/image04.mgz
- image_filepath: data/pitgland/binarized/images/image26.mgz
  label_filepath: data/pitgland/binarized/labels/image26.mgz
- image_filepath: data/pitgland/binarized/images/image22.mgz
  label_filepath: data/pitgland/binarized/labels/image22.mgz
- image_filepath: data/pitgland/binarized/images/image28.mgz
  label_filepath: data/pitgland/binarized/labels/image28.mgz
- image_filepath: data/pitgland/binarized/images/image09.mgz
  label_filepath: data/pitgland/binarized/labels/image09.mgz
- image_filepath: data/pitgland/binarized/images/image02.mgz
  label_filepath: data/pitgland/binarized/labels/image02.mgz
- image_filepath: data/pitgland/binarized/images/image08.mgz
  label_filepath: data/pitgland/binarized/labels/image08.mgz
- image_filepath: data/pitgland/binarized/images/image21.mgz
  label_filepath: data/pitgland/binarized/labels/image21.mgz
- image_filepath: data/pitgland/binarized/images/image12.mgz
  label_filepath: data/pitgland/binarized/labels/image12.mgz
- image_filepath: data/pitgland/binarized/images/image17.mgz
  label_filepath: data/pitgland/binarized/labels/image17.mgz
- image_filepath: data/pitgland/binarized/images/image23.mgz
  label_filepath: data/pitgland/binarized/labels/image23.mgz
- image_filepath: data/pitgland/binarized/images/image20.mgz
  label_filepath: data/pitgland/binarized/labels/image20.mgz
- image_filepath: data/pitgland/binarized/images/image29.mgz
  label_filepath: data/pitgland/binarized/labels/image29.mgz
- image_filepath: data/pitgland/binarized/images/image16.mgz
  label_filepath: data/pitgland/binarized/labels/image16.mgz
- image_filepath: data/pitgland/binarized/images/image10.mgz
  label_filepath: data/pitgland/binarized/labels/image10.mgz
- image_filepath: data/pitgland/binarized/images/image11.mgz
  label_filepath: data/pitgland/binarized/labels/image11.mgz
- image_filepath: data/pitgland/binarized/images/image19.mgz
  label_filepath: data/pitgland/binarized/labels/image19.mgz
- image_filepath: data/pitgland/binarized/images/image03.mgz
  label_filepath: data/pitgland/binarized/labels/image03.mgz
validation:
- image_filepath: data/pitgland/binarized/images/image01.mgz
  label_filepath: data/pitgland/binarized/labels/image01.mgz
- image_filepath: data/pitgland/binarized/images/image24.mgz
  label_filepath: data/pitgland/binarized/labels/image24.mgz
- image_filepath: data/pitgland/binarized/images/image06.mgz
  label_filepath: data/pitgland/binarized/labels/image06.mgz
- image_filepath: data/pitgland/binarized/images/image07.mgz
  label_filepath: data/pitgland/binarized/labels/image07.mgz
